// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: indexall/v1/resource.proto

package indexallv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationResourceServiceAddTag = "/indexall.v1.ResourceService/AddTag"
const OperationResourceServiceCreate = "/indexall.v1.ResourceService/Create"
const OperationResourceServiceDelete = "/indexall.v1.ResourceService/Delete"
const OperationResourceServiceGet = "/indexall.v1.ResourceService/Get"
const OperationResourceServiceGetByUrl = "/indexall.v1.ResourceService/GetByUrl"
const OperationResourceServiceList = "/indexall.v1.ResourceService/List"
const OperationResourceServiceRemoveTag = "/indexall.v1.ResourceService/RemoveTag"
const OperationResourceServiceSearch = "/indexall.v1.ResourceService/Search"
const OperationResourceServiceUpdate = "/indexall.v1.ResourceService/Update"

type ResourceServiceHTTPServer interface {
	AddTag(context.Context, *AddTagRequest) (*AddTagResponse, error)
	Create(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	Delete(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	Get(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	GetByUrl(context.Context, *GetByUrlRequest) (*GetByUrlResponse, error)
	List(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	RemoveTag(context.Context, *RemoveTagRequest) (*RemoveTagResponse, error)
	Search(context.Context, *SearchResourcesRequest) (*SearchResourcesResponse, error)
	Update(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error)
}

func RegisterResourceServiceHTTPServer(s *http.Server, srv ResourceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/resources", _ResourceService_Create1_HTTP_Handler(srv))
	r.PATCH("/v1/resources/{id}", _ResourceService_Update1_HTTP_Handler(srv))
	r.DELETE("/v1/resources/{id}", _ResourceService_Delete1_HTTP_Handler(srv))
	r.GET("/v1/resources/{id}", _ResourceService_Get0_HTTP_Handler(srv))
	r.GET("/v1/resources", _ResourceService_List1_HTTP_Handler(srv))
	r.GET("/v1/resources/search", _ResourceService_Search1_HTTP_Handler(srv))
	r.GET("/v1/resources/by-url", _ResourceService_GetByUrl0_HTTP_Handler(srv))
	r.POST("/v1/resources/{resource_id}/tags", _ResourceService_AddTag0_HTTP_Handler(srv))
	r.DELETE("/v1/resources/{resource_id}/tags/{tag_id}", _ResourceService_RemoveTag0_HTTP_Handler(srv))
}

func _ResourceService_Create1_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateResourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateResourceResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_Update1_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateResourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateResourceResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_Delete1_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteResourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeleteResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteResourceResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_Get0_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetResourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetResourceResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_List1_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListResourcesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListResourcesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListResourcesResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_Search1_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchResourcesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*SearchResourcesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchResourcesResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_GetByUrl0_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetByUrlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceGetByUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetByUrl(ctx, req.(*GetByUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetByUrlResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_AddTag0_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceAddTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddTag(ctx, req.(*AddTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddTagResponse)
		return ctx.Result(200, reply)
	}
}

func _ResourceService_RemoveTag0_HTTP_Handler(srv ResourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationResourceServiceRemoveTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveTag(ctx, req.(*RemoveTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveTagResponse)
		return ctx.Result(200, reply)
	}
}

type ResourceServiceHTTPClient interface {
	AddTag(ctx context.Context, req *AddTagRequest, opts ...http.CallOption) (rsp *AddTagResponse, err error)
	Create(ctx context.Context, req *CreateResourceRequest, opts ...http.CallOption) (rsp *CreateResourceResponse, err error)
	Delete(ctx context.Context, req *DeleteResourceRequest, opts ...http.CallOption) (rsp *DeleteResourceResponse, err error)
	Get(ctx context.Context, req *GetResourceRequest, opts ...http.CallOption) (rsp *GetResourceResponse, err error)
	GetByUrl(ctx context.Context, req *GetByUrlRequest, opts ...http.CallOption) (rsp *GetByUrlResponse, err error)
	List(ctx context.Context, req *ListResourcesRequest, opts ...http.CallOption) (rsp *ListResourcesResponse, err error)
	RemoveTag(ctx context.Context, req *RemoveTagRequest, opts ...http.CallOption) (rsp *RemoveTagResponse, err error)
	Search(ctx context.Context, req *SearchResourcesRequest, opts ...http.CallOption) (rsp *SearchResourcesResponse, err error)
	Update(ctx context.Context, req *UpdateResourceRequest, opts ...http.CallOption) (rsp *UpdateResourceResponse, err error)
}

type ResourceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewResourceServiceHTTPClient(client *http.Client) ResourceServiceHTTPClient {
	return &ResourceServiceHTTPClientImpl{client}
}

func (c *ResourceServiceHTTPClientImpl) AddTag(ctx context.Context, in *AddTagRequest, opts ...http.CallOption) (*AddTagResponse, error) {
	var out AddTagResponse
	pattern := "/v1/resources/{resource_id}/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationResourceServiceAddTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) Create(ctx context.Context, in *CreateResourceRequest, opts ...http.CallOption) (*CreateResourceResponse, error) {
	var out CreateResourceResponse
	pattern := "/v1/resources"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationResourceServiceCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) Delete(ctx context.Context, in *DeleteResourceRequest, opts ...http.CallOption) (*DeleteResourceResponse, error) {
	var out DeleteResourceResponse
	pattern := "/v1/resources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) Get(ctx context.Context, in *GetResourceRequest, opts ...http.CallOption) (*GetResourceResponse, error) {
	var out GetResourceResponse
	pattern := "/v1/resources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) GetByUrl(ctx context.Context, in *GetByUrlRequest, opts ...http.CallOption) (*GetByUrlResponse, error) {
	var out GetByUrlResponse
	pattern := "/v1/resources/by-url"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceGetByUrl))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) List(ctx context.Context, in *ListResourcesRequest, opts ...http.CallOption) (*ListResourcesResponse, error) {
	var out ListResourcesResponse
	pattern := "/v1/resources"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...http.CallOption) (*RemoveTagResponse, error) {
	var out RemoveTagResponse
	pattern := "/v1/resources/{resource_id}/tags/{tag_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceRemoveTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) Search(ctx context.Context, in *SearchResourcesRequest, opts ...http.CallOption) (*SearchResourcesResponse, error) {
	var out SearchResourcesResponse
	pattern := "/v1/resources/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationResourceServiceSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ResourceServiceHTTPClientImpl) Update(ctx context.Context, in *UpdateResourceRequest, opts ...http.CallOption) (*UpdateResourceResponse, error) {
	var out UpdateResourceResponse
	pattern := "/v1/resources/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationResourceServiceUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
