// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: indexall/v1/resource.proto

package indexallv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceStatus defines the state of a resource
type ResourceStatus int32

const (
	ResourceStatus_RESOURCE_STATUS_UNSPECIFIED ResourceStatus = 0
	ResourceStatus_RESOURCE_STATUS_ACTIVE      ResourceStatus = 1
	ResourceStatus_RESOURCE_STATUS_STALE       ResourceStatus = 2
	ResourceStatus_RESOURCE_STATUS_DELETED     ResourceStatus = 3
)

// Enum value maps for ResourceStatus.
var (
	ResourceStatus_name = map[int32]string{
		0: "RESOURCE_STATUS_UNSPECIFIED",
		1: "RESOURCE_STATUS_ACTIVE",
		2: "RESOURCE_STATUS_STALE",
		3: "RESOURCE_STATUS_DELETED",
	}
	ResourceStatus_value = map[string]int32{
		"RESOURCE_STATUS_UNSPECIFIED": 0,
		"RESOURCE_STATUS_ACTIVE":      1,
		"RESOURCE_STATUS_STALE":       2,
		"RESOURCE_STATUS_DELETED":     3,
	}
)

func (x ResourceStatus) Enum() *ResourceStatus {
	p := new(ResourceStatus)
	*p = x
	return p
}

func (x ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_resource_proto_enumTypes[0].Descriptor()
}

func (ResourceStatus) Type() protoreflect.EnumType {
	return &file_indexall_v1_resource_proto_enumTypes[0]
}

func (x ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceStatus.Descriptor instead.
func (ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{0}
}

type MatchSource int32

const (
	MatchSource_MATCH_SOURCE_UNSPECIFIED MatchSource = 0
	MatchSource_MATCH_SOURCE_TITLE       MatchSource = 1
	MatchSource_MATCH_SOURCE_DESCRIPTION MatchSource = 2
	MatchSource_MATCH_SOURCE_TAG         MatchSource = 3
	MatchSource_MATCH_SOURCE_ALIAS       MatchSource = 4
)

// Enum value maps for MatchSource.
var (
	MatchSource_name = map[int32]string{
		0: "MATCH_SOURCE_UNSPECIFIED",
		1: "MATCH_SOURCE_TITLE",
		2: "MATCH_SOURCE_DESCRIPTION",
		3: "MATCH_SOURCE_TAG",
		4: "MATCH_SOURCE_ALIAS",
	}
	MatchSource_value = map[string]int32{
		"MATCH_SOURCE_UNSPECIFIED": 0,
		"MATCH_SOURCE_TITLE":       1,
		"MATCH_SOURCE_DESCRIPTION": 2,
		"MATCH_SOURCE_TAG":         3,
		"MATCH_SOURCE_ALIAS":       4,
	}
)

func (x MatchSource) Enum() *MatchSource {
	p := new(MatchSource)
	*p = x
	return p
}

func (x MatchSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchSource) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_resource_proto_enumTypes[1].Descriptor()
}

func (MatchSource) Type() protoreflect.EnumType {
	return &file_indexall_v1_resource_proto_enumTypes[1]
}

func (x MatchSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchSource.Descriptor instead.
func (MatchSource) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{1}
}

type TagQuery_TagScope int32

const (
	TagQuery_DIRECT           TagQuery_TagScope = 0
	TagQuery_WITH_ANCESTORS   TagQuery_TagScope = 1
	TagQuery_WITH_DESCENDANTS TagQuery_TagScope = 2
)

// Enum value maps for TagQuery_TagScope.
var (
	TagQuery_TagScope_name = map[int32]string{
		0: "DIRECT",
		1: "WITH_ANCESTORS",
		2: "WITH_DESCENDANTS",
	}
	TagQuery_TagScope_value = map[string]int32{
		"DIRECT":           0,
		"WITH_ANCESTORS":   1,
		"WITH_DESCENDANTS": 2,
	}
)

func (x TagQuery_TagScope) Enum() *TagQuery_TagScope {
	p := new(TagQuery_TagScope)
	*p = x
	return p
}

func (x TagQuery_TagScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagQuery_TagScope) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_resource_proto_enumTypes[2].Descriptor()
}

func (TagQuery_TagScope) Type() protoreflect.EnumType {
	return &file_indexall_v1_resource_proto_enumTypes[2]
}

func (x TagQuery_TagScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagQuery_TagScope.Descriptor instead.
func (TagQuery_TagScope) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{19, 0}
}

type KeywordQuery_FieldScope int32

const (
	KeywordQuery_ALL         KeywordQuery_FieldScope = 0
	KeywordQuery_TITLE       KeywordQuery_FieldScope = 1
	KeywordQuery_DESCRIPTION KeywordQuery_FieldScope = 2
)

// Enum value maps for KeywordQuery_FieldScope.
var (
	KeywordQuery_FieldScope_name = map[int32]string{
		0: "ALL",
		1: "TITLE",
		2: "DESCRIPTION",
	}
	KeywordQuery_FieldScope_value = map[string]int32{
		"ALL":         0,
		"TITLE":       1,
		"DESCRIPTION": 2,
	}
)

func (x KeywordQuery_FieldScope) Enum() *KeywordQuery_FieldScope {
	p := new(KeywordQuery_FieldScope)
	*p = x
	return p
}

func (x KeywordQuery_FieldScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeywordQuery_FieldScope) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_resource_proto_enumTypes[3].Descriptor()
}

func (KeywordQuery_FieldScope) Type() protoreflect.EnumType {
	return &file_indexall_v1_resource_proto_enumTypes[3]
}

func (x KeywordQuery_FieldScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeywordQuery_FieldScope.Descriptor instead.
func (KeywordQuery_FieldScope) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{20, 0}
}

type KeywordQuery_TagScope int32

const (
	KeywordQuery_DIRECT           KeywordQuery_TagScope = 0
	KeywordQuery_WITH_ANCESTORS   KeywordQuery_TagScope = 1
	KeywordQuery_WITH_DESCENDANTS KeywordQuery_TagScope = 2
)

// Enum value maps for KeywordQuery_TagScope.
var (
	KeywordQuery_TagScope_name = map[int32]string{
		0: "DIRECT",
		1: "WITH_ANCESTORS",
		2: "WITH_DESCENDANTS",
	}
	KeywordQuery_TagScope_value = map[string]int32{
		"DIRECT":           0,
		"WITH_ANCESTORS":   1,
		"WITH_DESCENDANTS": 2,
	}
)

func (x KeywordQuery_TagScope) Enum() *KeywordQuery_TagScope {
	p := new(KeywordQuery_TagScope)
	*p = x
	return p
}

func (x KeywordQuery_TagScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeywordQuery_TagScope) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_resource_proto_enumTypes[4].Descriptor()
}

func (KeywordQuery_TagScope) Type() protoreflect.EnumType {
	return &file_indexall_v1_resource_proto_enumTypes[4]
}

func (x KeywordQuery_TagScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeywordQuery_TagScope.Descriptor instead.
func (KeywordQuery_TagScope) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{20, 1}
}

// ResourceTag represents a tag associated with a resource
type ResourceTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTag) Reset() {
	*x = ResourceTag{}
	mi := &file_indexall_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTag) ProtoMessage() {}

func (x *ResourceTag) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTag.ProtoReflect.Descriptor instead.
func (*ResourceTag) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceTag) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

// Resource represents an indexed resource from external systems
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ExternalId    *string                `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,6,opt,name=url,proto3,oneof" json:"url,omitempty"`
	OpenWith      *string                `protobuf:"bytes,7,opt,name=open_with,json=openWith,proto3,oneof" json:"open_with,omitempty"`
	Status        ResourceStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=indexall.v1.ResourceStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          []*ResourceTag         `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_indexall_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Resource) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *Resource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Resource) GetOpenWith() string {
	if x != nil && x.OpenWith != nil {
		return *x.OpenWith
	}
	return ""
}

func (x *Resource) GetStatus() ResourceStatus {
	if x != nil {
		return x.Status
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *Resource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Resource) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Resource) GetTags() []*ResourceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Source        *string                `protobuf:"bytes,4,opt,name=source,proto3,oneof" json:"source,omitempty"`
	ExternalId    *string                `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	OpenWith      *string                `protobuf:"bytes,6,opt,name=open_with,json=openWith,proto3,oneof" json:"open_with,omitempty"`
	TagIds        []string               `protobuf:"bytes,7,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResourceRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *CreateResourceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateResourceRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CreateResourceRequest) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *CreateResourceRequest) GetOpenWith() string {
	if x != nil && x.OpenWith != nil {
		return *x.OpenWith
	}
	return ""
}

func (x *CreateResourceRequest) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Tags          []*ResourceTag         `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResourceResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateResourceResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *CreateResourceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateResourceResponse) GetTags() []*ResourceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateResourceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	OpenWith      *string                `protobuf:"bytes,5,opt,name=open_with,json=openWith,proto3,oneof" json:"open_with,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResourceRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateResourceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateResourceRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *UpdateResourceRequest) GetOpenWith() string {
	if x != nil && x.OpenWith != nil {
		return *x.OpenWith
	}
	return ""
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{8}
}

func (x *GetResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ExternalId    *string                `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3,oneof" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,6,opt,name=url,proto3,oneof" json:"url,omitempty"`
	OpenWith      *string                `protobuf:"bytes,7,opt,name=open_with,json=openWith,proto3,oneof" json:"open_with,omitempty"`
	Metadata      *string                `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Status        ResourceStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=indexall.v1.ResourceStatus" json:"status,omitempty"`
	SyncedAt      *string                `protobuf:"bytes,10,opt,name=synced_at,json=syncedAt,proto3,oneof" json:"synced_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          []*ResourceTag         `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{9}
}

func (x *GetResourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResourceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetResourceResponse) GetExternalId() string {
	if x != nil && x.ExternalId != nil {
		return *x.ExternalId
	}
	return ""
}

func (x *GetResourceResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetResourceResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GetResourceResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *GetResourceResponse) GetOpenWith() string {
	if x != nil && x.OpenWith != nil {
		return *x.OpenWith
	}
	return ""
}

func (x *GetResourceResponse) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *GetResourceResponse) GetStatus() ResourceStatus {
	if x != nil {
		return x.Status
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *GetResourceResponse) GetSyncedAt() string {
	if x != nil && x.SyncedAt != nil {
		return *x.SyncedAt
	}
	return ""
}

func (x *GetResourceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetResourceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetResourceResponse) GetTags() []*ResourceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         *string                `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3,oneof" json:"tag_id,omitempty"`
	Status        *ResourceStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=indexall.v1.ResourceStatus,oneof" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourcesRequest) GetTagId() string {
	if x != nil && x.TagId != nil {
		return *x.TagId
	}
	return ""
}

func (x *ListResourcesRequest) GetStatus() ResourceStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *ListResourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceListItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{11}
}

func (x *ListResourcesResponse) GetItems() []*ResourceListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResourcesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResourcesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ResourceListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Status        ResourceStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=indexall.v1.ResourceStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Tags          []*ResourceTag         `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceListItem) Reset() {
	*x = ResourceListItem{}
	mi := &file_indexall_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceListItem) ProtoMessage() {}

func (x *ResourceListItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceListItem.ProtoReflect.Descriptor instead.
func (*ResourceListItem) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceListItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResourceListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceListItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ResourceListItem) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ResourceListItem) GetStatus() ResourceStatus {
	if x != nil {
		return x.Status
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *ResourceListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResourceListItem) GetTags() []*ResourceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SearchResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesRequest) Reset() {
	*x = SearchResourcesRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesRequest) ProtoMessage() {}

func (x *SearchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesRequest.ProtoReflect.Descriptor instead.
func (*SearchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResourcesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResourcesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ResourceSearchResult `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesResponse) Reset() {
	*x = SearchResourcesResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesResponse) ProtoMessage() {}

func (x *SearchResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesResponse.ProtoReflect.Descriptor instead.
func (*SearchResourcesResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResourcesResponse) GetItems() []*ResourceSearchResult {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResourcesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResourcesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResourcesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ResourceSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           *string                `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          []*TagInfo             `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	MatchSource   MatchSource            `protobuf:"varint,9,opt,name=match_source,json=matchSource,proto3,enum=indexall.v1.MatchSource" json:"match_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchResult) Reset() {
	*x = ResourceSearchResult{}
	mi := &file_indexall_v1_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchResult) ProtoMessage() {}

func (x *ResourceSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchResult.ProtoReflect.Descriptor instead.
func (*ResourceSearchResult) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceSearchResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResourceSearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceSearchResult) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ResourceSearchResult) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ResourceSearchResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResourceSearchResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ResourceSearchResult) GetTags() []*TagInfo {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResourceSearchResult) GetMatchSource() MatchSource {
	if x != nil {
		return x.MatchSource
	}
	return MatchSource_MATCH_SOURCE_UNSPECIFIED
}

type GetByUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUrlRequest) Reset() {
	*x = GetByUrlRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUrlRequest) ProtoMessage() {}

func (x *GetByUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUrlRequest.ProtoReflect.Descriptor instead.
func (*GetByUrlRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{16}
}

func (x *GetByUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetByUrlResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Resource      *GetByUrlResponse_Resource `protobuf:"bytes,1,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUrlResponse) Reset() {
	*x = GetByUrlResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUrlResponse) ProtoMessage() {}

func (x *GetByUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUrlResponse.ProtoReflect.Descriptor instead.
func (*GetByUrlResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{17}
}

func (x *GetByUrlResponse) GetResource() *GetByUrlResponse_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_indexall_v1_resource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{18}
}

func (x *TagInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TagInfo) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type TagQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagScope      TagQuery_TagScope      `protobuf:"varint,2,opt,name=tag_scope,json=tagScope,proto3,enum=indexall.v1.TagQuery_TagScope" json:"tag_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagQuery) Reset() {
	*x = TagQuery{}
	mi := &file_indexall_v1_resource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagQuery) ProtoMessage() {}

func (x *TagQuery) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagQuery.ProtoReflect.Descriptor instead.
func (*TagQuery) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{19}
}

func (x *TagQuery) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *TagQuery) GetTagScope() TagQuery_TagScope {
	if x != nil {
		return x.TagScope
	}
	return TagQuery_DIRECT
}

type KeywordQuery struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Keyword       string                  `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	FieldScope    KeywordQuery_FieldScope `protobuf:"varint,2,opt,name=field_scope,json=fieldScope,proto3,enum=indexall.v1.KeywordQuery_FieldScope" json:"field_scope,omitempty"`
	TagScope      KeywordQuery_TagScope   `protobuf:"varint,3,opt,name=tag_scope,json=tagScope,proto3,enum=indexall.v1.KeywordQuery_TagScope" json:"tag_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordQuery) Reset() {
	*x = KeywordQuery{}
	mi := &file_indexall_v1_resource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordQuery) ProtoMessage() {}

func (x *KeywordQuery) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordQuery.ProtoReflect.Descriptor instead.
func (*KeywordQuery) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{20}
}

func (x *KeywordQuery) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *KeywordQuery) GetFieldScope() KeywordQuery_FieldScope {
	if x != nil {
		return x.FieldScope
	}
	return KeywordQuery_ALL
}

func (x *KeywordQuery) GetTagScope() KeywordQuery_TagScope {
	if x != nil {
		return x.TagScope
	}
	return KeywordQuery_DIRECT
}

type ResourceQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*ResourceQueryRequest_TagQuery
	//	*ResourceQueryRequest_KeywordQuery
	Query         isResourceQueryRequest_Query `protobuf_oneof:"query"`
	Page          int32                        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                        `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                       `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQueryRequest) Reset() {
	*x = ResourceQueryRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQueryRequest) ProtoMessage() {}

func (x *ResourceQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQueryRequest.ProtoReflect.Descriptor instead.
func (*ResourceQueryRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{21}
}

func (x *ResourceQueryRequest) GetQuery() isResourceQueryRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ResourceQueryRequest) GetTagQuery() *TagQuery {
	if x != nil {
		if x, ok := x.Query.(*ResourceQueryRequest_TagQuery); ok {
			return x.TagQuery
		}
	}
	return nil
}

func (x *ResourceQueryRequest) GetKeywordQuery() *KeywordQuery {
	if x != nil {
		if x, ok := x.Query.(*ResourceQueryRequest_KeywordQuery); ok {
			return x.KeywordQuery
		}
	}
	return nil
}

func (x *ResourceQueryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ResourceQueryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResourceQueryRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type isResourceQueryRequest_Query interface {
	isResourceQueryRequest_Query()
}

type ResourceQueryRequest_TagQuery struct {
	TagQuery *TagQuery `protobuf:"bytes,1,opt,name=tag_query,json=tagQuery,proto3,oneof"`
}

type ResourceQueryRequest_KeywordQuery struct {
	KeywordQuery *KeywordQuery `protobuf:"bytes,2,opt,name=keyword_query,json=keywordQuery,proto3,oneof"`
}

func (*ResourceQueryRequest_TagQuery) isResourceQueryRequest_Query() {}

func (*ResourceQueryRequest_KeywordQuery) isResourceQueryRequest_Query() {}

type ResourceQueryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*ResourceSearchResult `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceQueryResponse) Reset() {
	*x = ResourceQueryResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceQueryResponse) ProtoMessage() {}

func (x *ResourceQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceQueryResponse.ProtoReflect.Descriptor instead.
func (*ResourceQueryResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{22}
}

func (x *ResourceQueryResponse) GetItems() []*ResourceSearchResult {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResourceQueryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ResourceQueryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ResourceQueryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AddTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TagId         string                 `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagRequest) Reset() {
	*x = AddTagRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagRequest) ProtoMessage() {}

func (x *AddTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagRequest.ProtoReflect.Descriptor instead.
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{23}
}

func (x *AddTagRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AddTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

type AddTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagResponse) Reset() {
	*x = AddTagResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagResponse) ProtoMessage() {}

func (x *AddTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagResponse.ProtoReflect.Descriptor instead.
func (*AddTagResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{24}
}

func (x *AddTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TagId         string                 `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagRequest) Reset() {
	*x = RemoveTagRequest{}
	mi := &file_indexall_v1_resource_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagRequest) ProtoMessage() {}

func (x *RemoveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveTagRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RemoveTagRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

type RemoveTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagResponse) Reset() {
	*x = RemoveTagResponse{}
	mi := &file_indexall_v1_resource_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagResponse) ProtoMessage() {}

func (x *RemoveTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagResponse.ProtoReflect.Descriptor instead.
func (*RemoveTagResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetByUrlResponse_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []*ResourceTag         `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUrlResponse_Resource) Reset() {
	*x = GetByUrlResponse_Resource{}
	mi := &file_indexall_v1_resource_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUrlResponse_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUrlResponse_Resource) ProtoMessage() {}

func (x *GetByUrlResponse_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_resource_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUrlResponse_Resource.ProtoReflect.Descriptor instead.
func (*GetByUrlResponse_Resource) Descriptor() ([]byte, []int) {
	return file_indexall_v1_resource_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetByUrlResponse_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetByUrlResponse_Resource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetByUrlResponse_Resource) GetTags() []*ResourceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_indexall_v1_resource_proto protoreflect.FileDescriptor

const file_indexall_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1aindexall/v1/resource.proto\x12\vindexall.v1\x1a\x1cgoogle/api/annotations.proto\"V\n" +
	"\vResourceTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color\"\xa5\x03\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\vexternal_id\x18\x03 \x01(\tH\x00R\n" +
	"externalId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x06 \x01(\tH\x02R\x03url\x88\x01\x01\x12 \n" +
	"\topen_with\x18\a \x01(\tH\x03R\bopenWith\x88\x01\x01\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.indexall.v1.ResourceStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12,\n" +
	"\x04tags\x18\v \x03(\v2\x18.indexall.v1.ResourceTagR\x04tagsB\x0e\n" +
	"\f_external_idB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_urlB\f\n" +
	"\n" +
	"_open_with\"\xaa\x02\n" +
	"\x15CreateResourceRequest\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x04 \x01(\tH\x02R\x06source\x88\x01\x01\x12$\n" +
	"\vexternal_id\x18\x05 \x01(\tH\x03R\n" +
	"externalId\x88\x01\x01\x12 \n" +
	"\topen_with\x18\x06 \x01(\tH\x04R\bopenWith\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\a \x03(\tR\x06tagIdsB\x06\n" +
	"\x04_urlB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_external_idB\f\n" +
	"\n" +
	"_open_with\"\xc2\x01\n" +
	"\x16CreateResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12,\n" +
	"\x04tags\x18\x05 \x03(\v2\x18.indexall.v1.ResourceTagR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\x06\n" +
	"\x04_url\"\xd2\x01\n" +
	"\x15UpdateResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x02R\x03url\x88\x01\x01\x12 \n" +
	"\topen_with\x18\x05 \x01(\tH\x03R\bopenWith\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_urlB\f\n" +
	"\n" +
	"_open_with\"2\n" +
	"\x16UpdateResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15DeleteResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12GetResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8e\x04\n" +
	"\x13GetResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\vexternal_id\x18\x03 \x01(\tH\x00R\n" +
	"externalId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x06 \x01(\tH\x02R\x03url\x88\x01\x01\x12 \n" +
	"\topen_with\x18\a \x01(\tH\x03R\bopenWith\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\b \x01(\tH\x04R\bmetadata\x88\x01\x01\x123\n" +
	"\x06status\x18\t \x01(\x0e2\x1b.indexall.v1.ResourceStatusR\x06status\x12 \n" +
	"\tsynced_at\x18\n" +
	" \x01(\tH\x05R\bsyncedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12,\n" +
	"\x04tags\x18\r \x03(\v2\x18.indexall.v1.ResourceTagR\x04tagsB\x0e\n" +
	"\f_external_idB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_urlB\f\n" +
	"\n" +
	"_open_withB\v\n" +
	"\t_metadataB\f\n" +
	"\n" +
	"_synced_at\"\xb3\x01\n" +
	"\x14ListResourcesRequest\x12\x1a\n" +
	"\x06tag_id\x18\x01 \x01(\tH\x00R\x05tagId\x88\x01\x01\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.indexall.v1.ResourceStatusH\x01R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\t\n" +
	"\a_tag_idB\t\n" +
	"\a_status\"\x93\x01\n" +
	"\x15ListResourcesResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.indexall.v1.ResourceListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa8\x02\n" +
	"\x10ResourceListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x01R\x03url\x88\x01\x01\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.indexall.v1.ResourceStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12,\n" +
	"\x04tags\x18\b \x03(\v2\x18.indexall.v1.ResourceTagR\x04tagsB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_url\"_\n" +
	"\x16SearchResourcesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x99\x01\n" +
	"\x17SearchResourcesResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.indexall.v1.ResourceSearchResultR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xcf\x02\n" +
	"\x14ResourceSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x01R\x03url\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12(\n" +
	"\x04tags\x18\b \x03(\v2\x14.indexall.v1.TagInfoR\x04tags\x12;\n" +
	"\fmatch_source\x18\t \x01(\x0e2\x18.indexall.v1.MatchSourceR\vmatchSourceB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_url\"#\n" +
	"\x0fGetByUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xc8\x01\n" +
	"\x10GetByUrlResponse\x12G\n" +
	"\bresource\x18\x01 \x01(\v2&.indexall.v1.GetByUrlResponse.ResourceH\x00R\bresource\x88\x01\x01\x1a^\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12,\n" +
	"\x04tags\x18\x03 \x03(\v2\x18.indexall.v1.ResourceTagR\x04tagsB\v\n" +
	"\t_resource\"~\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliasesB\x0e\n" +
	"\f_description\"\xa0\x01\n" +
	"\bTagQuery\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12;\n" +
	"\ttag_scope\x18\x02 \x01(\x0e2\x1e.indexall.v1.TagQuery.TagScopeR\btagScope\"@\n" +
	"\bTagScope\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\x12\n" +
	"\x0eWITH_ANCESTORS\x10\x01\x12\x14\n" +
	"\x10WITH_DESCENDANTS\x10\x02\"\xa5\x02\n" +
	"\fKeywordQuery\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12E\n" +
	"\vfield_scope\x18\x02 \x01(\x0e2$.indexall.v1.KeywordQuery.FieldScopeR\n" +
	"fieldScope\x12?\n" +
	"\ttag_scope\x18\x03 \x01(\x0e2\".indexall.v1.KeywordQuery.TagScopeR\btagScope\"1\n" +
	"\n" +
	"FieldScope\x12\a\n" +
	"\x03ALL\x10\x00\x12\t\n" +
	"\x05TITLE\x10\x01\x12\x0f\n" +
	"\vDESCRIPTION\x10\x02\"@\n" +
	"\bTagScope\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\x12\n" +
	"\x0eWITH_ANCESTORS\x10\x01\x12\x14\n" +
	"\x10WITH_DESCENDANTS\x10\x02\"\xe1\x01\n" +
	"\x14ResourceQueryRequest\x124\n" +
	"\ttag_query\x18\x01 \x01(\v2\x15.indexall.v1.TagQueryH\x00R\btagQuery\x12@\n" +
	"\rkeyword_query\x18\x02 \x01(\v2\x19.indexall.v1.KeywordQueryH\x00R\fkeywordQuery\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortByB\a\n" +
	"\x05query\"\x97\x01\n" +
	"\x15ResourceQueryResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.indexall.v1.ResourceSearchResultR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"G\n" +
	"\rAddTagRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\tR\x05tagId\"*\n" +
	"\x0eAddTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x10RemoveTagRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\tR\x05tagId\"-\n" +
	"\x11RemoveTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x85\x01\n" +
	"\x0eResourceStatus\x12\x1f\n" +
	"\x1bRESOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESOURCE_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15RESOURCE_STATUS_STALE\x10\x02\x12\x1b\n" +
	"\x17RESOURCE_STATUS_DELETED\x10\x03*\x8f\x01\n" +
	"\vMatchSource\x12\x1c\n" +
	"\x18MATCH_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MATCH_SOURCE_TITLE\x10\x01\x12\x1c\n" +
	"\x18MATCH_SOURCE_DESCRIPTION\x10\x02\x12\x14\n" +
	"\x10MATCH_SOURCE_TAG\x10\x03\x12\x16\n" +
	"\x12MATCH_SOURCE_ALIAS\x10\x042\x8b\a\n" +
	"\x0fResourceService\x12k\n" +
	"\x06Create\x12\".indexall.v1.CreateResourceRequest\x1a#.indexall.v1.CreateResourceResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/resources\x12p\n" +
	"\x06Update\x12\".indexall.v1.UpdateResourceRequest\x1a#.indexall.v1.UpdateResourceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*2\x12/v1/resources/{id}\x12m\n" +
	"\x06Delete\x12\".indexall.v1.DeleteResourceRequest\x1a#.indexall.v1.DeleteResourceResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/resources/{id}\x12d\n" +
	"\x03Get\x12\x1f.indexall.v1.GetResourceRequest\x1a .indexall.v1.GetResourceResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/resources/{id}\x12n\n" +
	"\x05Query\x12!.indexall.v1.ResourceQueryRequest\x1a\".indexall.v1.ResourceQueryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/resources/query\x12e\n" +
	"\bGetByUrl\x12\x1c.indexall.v1.GetByUrlRequest\x1a\x1d.indexall.v1.GetByUrlResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/resources/by-url\x12n\n" +
	"\x06AddTag\x12\x1a.indexall.v1.AddTagRequest\x1a\x1b.indexall.v1.AddTagResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/resources/{resource_id}/tags\x12}\n" +
	"\tRemoveTag\x12\x1d.indexall.v1.RemoveTagRequest\x1a\x1e.indexall.v1.RemoveTagResponse\"1\x82\xd3\xe4\x93\x02+*)/v1/resources/{resource_id}/tags/{tag_id}BFZDgithub.com/construct/indexall/internal/gen/pb/indexall/v1;indexallv1b\x06proto3"

var (
	file_indexall_v1_resource_proto_rawDescOnce sync.Once
	file_indexall_v1_resource_proto_rawDescData []byte
)

func file_indexall_v1_resource_proto_rawDescGZIP() []byte {
	file_indexall_v1_resource_proto_rawDescOnce.Do(func() {
		file_indexall_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexall_v1_resource_proto_rawDesc), len(file_indexall_v1_resource_proto_rawDesc)))
	})
	return file_indexall_v1_resource_proto_rawDescData
}

var file_indexall_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_indexall_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_indexall_v1_resource_proto_goTypes = []any{
	(ResourceStatus)(0),               // 0: indexall.v1.ResourceStatus
	(MatchSource)(0),                  // 1: indexall.v1.MatchSource
	(TagQuery_TagScope)(0),            // 2: indexall.v1.TagQuery.TagScope
	(KeywordQuery_FieldScope)(0),      // 3: indexall.v1.KeywordQuery.FieldScope
	(KeywordQuery_TagScope)(0),        // 4: indexall.v1.KeywordQuery.TagScope
	(*ResourceTag)(nil),               // 5: indexall.v1.ResourceTag
	(*Resource)(nil),                  // 6: indexall.v1.Resource
	(*CreateResourceRequest)(nil),     // 7: indexall.v1.CreateResourceRequest
	(*CreateResourceResponse)(nil),    // 8: indexall.v1.CreateResourceResponse
	(*UpdateResourceRequest)(nil),     // 9: indexall.v1.UpdateResourceRequest
	(*UpdateResourceResponse)(nil),    // 10: indexall.v1.UpdateResourceResponse
	(*DeleteResourceRequest)(nil),     // 11: indexall.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),    // 12: indexall.v1.DeleteResourceResponse
	(*GetResourceRequest)(nil),        // 13: indexall.v1.GetResourceRequest
	(*GetResourceResponse)(nil),       // 14: indexall.v1.GetResourceResponse
	(*ListResourcesRequest)(nil),      // 15: indexall.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),     // 16: indexall.v1.ListResourcesResponse
	(*ResourceListItem)(nil),          // 17: indexall.v1.ResourceListItem
	(*SearchResourcesRequest)(nil),    // 18: indexall.v1.SearchResourcesRequest
	(*SearchResourcesResponse)(nil),   // 19: indexall.v1.SearchResourcesResponse
	(*ResourceSearchResult)(nil),      // 20: indexall.v1.ResourceSearchResult
	(*GetByUrlRequest)(nil),           // 21: indexall.v1.GetByUrlRequest
	(*GetByUrlResponse)(nil),          // 22: indexall.v1.GetByUrlResponse
	(*TagInfo)(nil),                   // 23: indexall.v1.TagInfo
	(*TagQuery)(nil),                  // 24: indexall.v1.TagQuery
	(*KeywordQuery)(nil),              // 25: indexall.v1.KeywordQuery
	(*ResourceQueryRequest)(nil),      // 26: indexall.v1.ResourceQueryRequest
	(*ResourceQueryResponse)(nil),     // 27: indexall.v1.ResourceQueryResponse
	(*AddTagRequest)(nil),             // 28: indexall.v1.AddTagRequest
	(*AddTagResponse)(nil),            // 29: indexall.v1.AddTagResponse
	(*RemoveTagRequest)(nil),          // 30: indexall.v1.RemoveTagRequest
	(*RemoveTagResponse)(nil),         // 31: indexall.v1.RemoveTagResponse
	(*GetByUrlResponse_Resource)(nil), // 32: indexall.v1.GetByUrlResponse.Resource
}
var file_indexall_v1_resource_proto_depIdxs = []int32{
	0,  // 0: indexall.v1.Resource.status:type_name -> indexall.v1.ResourceStatus
	5,  // 1: indexall.v1.Resource.tags:type_name -> indexall.v1.ResourceTag
	5,  // 2: indexall.v1.CreateResourceResponse.tags:type_name -> indexall.v1.ResourceTag
	0,  // 3: indexall.v1.GetResourceResponse.status:type_name -> indexall.v1.ResourceStatus
	5,  // 4: indexall.v1.GetResourceResponse.tags:type_name -> indexall.v1.ResourceTag
	0,  // 5: indexall.v1.ListResourcesRequest.status:type_name -> indexall.v1.ResourceStatus
	17, // 6: indexall.v1.ListResourcesResponse.items:type_name -> indexall.v1.ResourceListItem
	0,  // 7: indexall.v1.ResourceListItem.status:type_name -> indexall.v1.ResourceStatus
	5,  // 8: indexall.v1.ResourceListItem.tags:type_name -> indexall.v1.ResourceTag
	20, // 9: indexall.v1.SearchResourcesResponse.items:type_name -> indexall.v1.ResourceSearchResult
	23, // 10: indexall.v1.ResourceSearchResult.tags:type_name -> indexall.v1.TagInfo
	1,  // 11: indexall.v1.ResourceSearchResult.match_source:type_name -> indexall.v1.MatchSource
	32, // 12: indexall.v1.GetByUrlResponse.resource:type_name -> indexall.v1.GetByUrlResponse.Resource
	2,  // 13: indexall.v1.TagQuery.tag_scope:type_name -> indexall.v1.TagQuery.TagScope
	3,  // 14: indexall.v1.KeywordQuery.field_scope:type_name -> indexall.v1.KeywordQuery.FieldScope
	4,  // 15: indexall.v1.KeywordQuery.tag_scope:type_name -> indexall.v1.KeywordQuery.TagScope
	24, // 16: indexall.v1.ResourceQueryRequest.tag_query:type_name -> indexall.v1.TagQuery
	25, // 17: indexall.v1.ResourceQueryRequest.keyword_query:type_name -> indexall.v1.KeywordQuery
	20, // 18: indexall.v1.ResourceQueryResponse.items:type_name -> indexall.v1.ResourceSearchResult
	5,  // 19: indexall.v1.GetByUrlResponse.Resource.tags:type_name -> indexall.v1.ResourceTag
	7,  // 20: indexall.v1.ResourceService.Create:input_type -> indexall.v1.CreateResourceRequest
	9,  // 21: indexall.v1.ResourceService.Update:input_type -> indexall.v1.UpdateResourceRequest
	11, // 22: indexall.v1.ResourceService.Delete:input_type -> indexall.v1.DeleteResourceRequest
	13, // 23: indexall.v1.ResourceService.Get:input_type -> indexall.v1.GetResourceRequest
	26, // 24: indexall.v1.ResourceService.Query:input_type -> indexall.v1.ResourceQueryRequest
	21, // 25: indexall.v1.ResourceService.GetByUrl:input_type -> indexall.v1.GetByUrlRequest
	28, // 26: indexall.v1.ResourceService.AddTag:input_type -> indexall.v1.AddTagRequest
	30, // 27: indexall.v1.ResourceService.RemoveTag:input_type -> indexall.v1.RemoveTagRequest
	8,  // 28: indexall.v1.ResourceService.Create:output_type -> indexall.v1.CreateResourceResponse
	10, // 29: indexall.v1.ResourceService.Update:output_type -> indexall.v1.UpdateResourceResponse
	12, // 30: indexall.v1.ResourceService.Delete:output_type -> indexall.v1.DeleteResourceResponse
	14, // 31: indexall.v1.ResourceService.Get:output_type -> indexall.v1.GetResourceResponse
	27, // 32: indexall.v1.ResourceService.Query:output_type -> indexall.v1.ResourceQueryResponse
	22, // 33: indexall.v1.ResourceService.GetByUrl:output_type -> indexall.v1.GetByUrlResponse
	29, // 34: indexall.v1.ResourceService.AddTag:output_type -> indexall.v1.AddTagResponse
	31, // 35: indexall.v1.ResourceService.RemoveTag:output_type -> indexall.v1.RemoveTagResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_indexall_v1_resource_proto_init() }
func file_indexall_v1_resource_proto_init() {
	if File_indexall_v1_resource_proto != nil {
		return
	}
	file_indexall_v1_resource_proto_msgTypes[0].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[1].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[2].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[3].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[4].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[9].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[10].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[12].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[15].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[17].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[18].OneofWrappers = []any{}
	file_indexall_v1_resource_proto_msgTypes[21].OneofWrappers = []any{
		(*ResourceQueryRequest_TagQuery)(nil),
		(*ResourceQueryRequest_KeywordQuery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexall_v1_resource_proto_rawDesc), len(file_indexall_v1_resource_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexall_v1_resource_proto_goTypes,
		DependencyIndexes: file_indexall_v1_resource_proto_depIdxs,
		EnumInfos:         file_indexall_v1_resource_proto_enumTypes,
		MessageInfos:      file_indexall_v1_resource_proto_msgTypes,
	}.Build()
	File_indexall_v1_resource_proto = out.File
	file_indexall_v1_resource_proto_goTypes = nil
	file_indexall_v1_resource_proto_depIdxs = nil
}
