// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: indexall/v1/tag.proto

package indexallv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTagsRequest_TagScope int32

const (
	SearchTagsRequest_DIRECT           SearchTagsRequest_TagScope = 0
	SearchTagsRequest_WITH_ANCESTORS   SearchTagsRequest_TagScope = 1
	SearchTagsRequest_WITH_DESCENDANTS SearchTagsRequest_TagScope = 2
)

// Enum value maps for SearchTagsRequest_TagScope.
var (
	SearchTagsRequest_TagScope_name = map[int32]string{
		0: "DIRECT",
		1: "WITH_ANCESTORS",
		2: "WITH_DESCENDANTS",
	}
	SearchTagsRequest_TagScope_value = map[string]int32{
		"DIRECT":           0,
		"WITH_ANCESTORS":   1,
		"WITH_DESCENDANTS": 2,
	}
)

func (x SearchTagsRequest_TagScope) Enum() *SearchTagsRequest_TagScope {
	p := new(SearchTagsRequest_TagScope)
	*p = x
	return p
}

func (x SearchTagsRequest_TagScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTagsRequest_TagScope) Descriptor() protoreflect.EnumDescriptor {
	return file_indexall_v1_tag_proto_enumTypes[0].Descriptor()
}

func (SearchTagsRequest_TagScope) Type() protoreflect.EnumType {
	return &file_indexall_v1_tag_proto_enumTypes[0]
}

func (x SearchTagsRequest_TagScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTagsRequest_TagScope.Descriptor instead.
func (SearchTagsRequest_TagScope) EnumDescriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{13, 0}
}

// Tag represents a label/classification for resources
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ParentIds     []string               `protobuf:"bytes,5,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	ResourceCount int32                  `protobuf:"varint,6,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_indexall_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Tag) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Tag) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *Tag) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *Tag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,2,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ParentIds     []string               `protobuf:"bytes,4,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CreateTagRequest) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CreateTagRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ParentIds     []string               `protobuf:"bytes,5,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTagResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagResponse) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CreateTagResponse) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CreateTagResponse) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *CreateTagResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{7}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagListItem         `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{8}
}

func (x *ListTagsResponse) GetTags() []*TagListItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ParentIds     []string               `protobuf:"bytes,5,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	ResourceCount int32                  `protobuf:"varint,6,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListItem) Reset() {
	*x = TagListItem{}
	mi := &file_indexall_v1_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListItem) ProtoMessage() {}

func (x *TagListItem) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListItem.ProtoReflect.Descriptor instead.
func (*TagListItem) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{9}
}

func (x *TagListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagListItem) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *TagListItem) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *TagListItem) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *TagListItem) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type TagTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	ResourceCount int32                  `protobuf:"varint,4,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	Children      []*TagTreeNode         `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagTreeNode) Reset() {
	*x = TagTreeNode{}
	mi := &file_indexall_v1_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagTreeNode) ProtoMessage() {}

func (x *TagTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagTreeNode.ProtoReflect.Descriptor instead.
func (*TagTreeNode) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{10}
}

func (x *TagTreeNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagTreeNode) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *TagTreeNode) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TagTreeNode) GetChildren() []*TagTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{11}
}

type GetTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*TagTreeNode         `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeResponse) Reset() {
	*x = GetTreeResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeResponse) ProtoMessage() {}

func (x *GetTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTreeResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{12}
}

func (x *GetTreeResponse) GetRoots() []*TagTreeNode {
	if x != nil {
		return x.Roots
	}
	return nil
}

type SearchTagsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Query         string                     `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TagScope      SearchTagsRequest_TagScope `protobuf:"varint,2,opt,name=tag_scope,json=tagScope,proto3,enum=indexall.v1.SearchTagsRequest_TagScope" json:"tag_scope,omitempty"`
	Limit         int32                      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                      `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsRequest) Reset() {
	*x = SearchTagsRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsRequest) ProtoMessage() {}

func (x *SearchTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsRequest.ProtoReflect.Descriptor instead.
func (*SearchTagsRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{13}
}

func (x *SearchTagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTagsRequest) GetTagScope() SearchTagsRequest_TagScope {
	if x != nil {
		return x.TagScope
	}
	return SearchTagsRequest_DIRECT
}

func (x *SearchTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchTagsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TagSearchResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsResponse) Reset() {
	*x = SearchTagsResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsResponse) ProtoMessage() {}

func (x *SearchTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsResponse.ProtoReflect.Descriptor instead.
func (*SearchTagsResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{14}
}

func (x *SearchTagsResponse) GetResults() []*TagSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchTagsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TagSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Aliases       []string               `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ResourceCount int32                  `protobuf:"varint,6,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	// Ancestor tag names from root to immediate parent, used to show match path in UI.
	// e.g. ["Learning", "Python"] means this tag lives under Learning > Python.
	Ancestors     []string `protobuf:"bytes,7,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSearchResult) Reset() {
	*x = TagSearchResult{}
	mi := &file_indexall_v1_tag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSearchResult) ProtoMessage() {}

func (x *TagSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSearchResult.ProtoReflect.Descriptor instead.
func (*TagSearchResult) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{15}
}

func (x *TagSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSearchResult) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *TagSearchResult) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TagSearchResult) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *TagSearchResult) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TagSearchResult) GetAncestors() []string {
	if x != nil {
		return x.Ancestors
	}
	return nil
}

type AddAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAliasRequest) Reset() {
	*x = AddAliasRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAliasRequest) ProtoMessage() {}

func (x *AddAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAliasRequest.ProtoReflect.Descriptor instead.
func (*AddAliasRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{16}
}

func (x *AddAliasRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *AddAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type AddAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAliasResponse) Reset() {
	*x = AddAliasResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAliasResponse) ProtoMessage() {}

func (x *AddAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAliasResponse.ProtoReflect.Descriptor instead.
func (*AddAliasResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{17}
}

func (x *AddAliasResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddAliasResponse) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type RemoveAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AliasId       string                 `protobuf:"bytes,1,opt,name=alias_id,json=aliasId,proto3" json:"alias_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAliasRequest) Reset() {
	*x = RemoveAliasRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAliasRequest) ProtoMessage() {}

func (x *RemoveAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAliasRequest.ProtoReflect.Descriptor instead.
func (*RemoveAliasRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveAliasRequest) GetAliasId() string {
	if x != nil {
		return x.AliasId
	}
	return ""
}

type RemoveAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAliasResponse) Reset() {
	*x = RemoveAliasResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAliasResponse) ProtoMessage() {}

func (x *RemoveAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAliasResponse.ProtoReflect.Descriptor instead.
func (*RemoveAliasResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveAliasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParentRequest) Reset() {
	*x = AddParentRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParentRequest) ProtoMessage() {}

func (x *AddParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParentRequest.ProtoReflect.Descriptor instead.
func (*AddParentRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{20}
}

func (x *AddParentRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *AddParentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type AddParentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParentResponse) Reset() {
	*x = AddParentResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParentResponse) ProtoMessage() {}

func (x *AddParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParentResponse.ProtoReflect.Descriptor instead.
func (*AddParentResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{21}
}

func (x *AddParentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParentRequest) Reset() {
	*x = RemoveParentRequest{}
	mi := &file_indexall_v1_tag_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParentRequest) ProtoMessage() {}

func (x *RemoveParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParentRequest.ProtoReflect.Descriptor instead.
func (*RemoveParentRequest) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveParentRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *RemoveParentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type RemoveParentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParentResponse) Reset() {
	*x = RemoveParentResponse{}
	mi := &file_indexall_v1_tag_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParentResponse) ProtoMessage() {}

func (x *RemoveParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexall_v1_tag_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParentResponse.ProtoReflect.Descriptor instead.
func (*RemoveParentResponse) Descriptor() ([]byte, []int) {
	return file_indexall_v1_tag_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveParentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_indexall_v1_tag_proto protoreflect.FileDescriptor

const file_indexall_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x15indexall/v1/tag.proto\x12\vindexall.v1\x1a\x1cgoogle/api/annotations.proto\"\xec\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x05 \x03(\tR\tparentIds\x12%\n" +
	"\x0eresource_count\x18\x06 \x01(\x05R\rresourceCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAtB\b\n" +
	"\x06_color\"\x84\x01\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x02 \x01(\tH\x00R\x05color\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x04 \x03(\tR\tparentIdsB\b\n" +
	"\x06_color\"\xb4\x01\n" +
	"\x11CreateTagResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x05 \x03(\tR\tparentIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\b\n" +
	"\x06_color\"i\n" +
	"\x10UpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x01R\x05color\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_color\"-\n" +
	"\x11UpdateTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fListTagsRequest\"@\n" +
	"\x10ListTagsResponse\x12,\n" +
	"\x04tags\x18\x01 \x03(\v2\x18.indexall.v1.TagListItemR\x04tags\"\xb6\x01\n" +
	"\vTagListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x05 \x03(\tR\tparentIds\x12%\n" +
	"\x0eresource_count\x18\x06 \x01(\x05R\rresourceCountB\b\n" +
	"\x06_color\"\xb3\x01\n" +
	"\vTagTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01\x12%\n" +
	"\x0eresource_count\x18\x04 \x01(\x05R\rresourceCount\x124\n" +
	"\bchildren\x18\x05 \x03(\v2\x18.indexall.v1.TagTreeNodeR\bchildrenB\b\n" +
	"\x06_color\"\x10\n" +
	"\x0eGetTreeRequest\"A\n" +
	"\x0fGetTreeResponse\x12.\n" +
	"\x05roots\x18\x01 \x03(\v2\x18.indexall.v1.TagTreeNodeR\x05roots\"\xdf\x01\n" +
	"\x11SearchTagsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12D\n" +
	"\ttag_scope\x18\x02 \x01(\x0e2'.indexall.v1.SearchTagsRequest.TagScopeR\btagScope\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"@\n" +
	"\bTagScope\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\x12\n" +
	"\x0eWITH_ANCESTORS\x10\x01\x12\x14\n" +
	"\x10WITH_DESCENDANTS\x10\x02\"b\n" +
	"\x12SearchTagsResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.indexall.v1.TagSearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf0\x01\n" +
	"\x0fTagSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x18\n" +
	"\aaliases\x18\x05 \x03(\tR\aaliases\x12%\n" +
	"\x0eresource_count\x18\x06 \x01(\x05R\rresourceCount\x12\x1c\n" +
	"\tancestors\x18\a \x03(\tR\tancestorsB\b\n" +
	"\x06_colorB\x0e\n" +
	"\f_description\">\n" +
	"\x0fAddAliasRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"8\n" +
	"\x10AddAliasResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"/\n" +
	"\x12RemoveAliasRequest\x12\x19\n" +
	"\balias_id\x18\x01 \x01(\tR\aaliasId\"/\n" +
	"\x13RemoveAliasResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x10AddParentRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"-\n" +
	"\x11AddParentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x13RemoveParentRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"0\n" +
	"\x14RemoveParentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa6\b\n" +
	"\n" +
	"TagService\x12\\\n" +
	"\x06Create\x12\x1d.indexall.v1.CreateTagRequest\x1a\x1e.indexall.v1.CreateTagResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/tags\x12a\n" +
	"\x06Update\x12\x1d.indexall.v1.UpdateTagRequest\x1a\x1e.indexall.v1.UpdateTagResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*2\r/v1/tags/{id}\x12^\n" +
	"\x06Delete\x12\x1d.indexall.v1.DeleteTagRequest\x1a\x1e.indexall.v1.DeleteTagResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/tags/{id}\x12U\n" +
	"\x04List\x12\x1c.indexall.v1.ListTagsRequest\x1a\x1d.indexall.v1.ListTagsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/tags\x12[\n" +
	"\aGetTree\x12\x1b.indexall.v1.GetTreeRequest\x1a\x1c.indexall.v1.GetTreeResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/tags/tree\x12b\n" +
	"\x06Search\x12\x1e.indexall.v1.SearchTagsRequest\x1a\x1f.indexall.v1.SearchTagsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tags/search\x12m\n" +
	"\bAddAlias\x12\x1c.indexall.v1.AddAliasRequest\x1a\x1d.indexall.v1.AddAliasResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/tags/{tag_id}/aliases\x12u\n" +
	"\vRemoveAlias\x12\x1f.indexall.v1.RemoveAliasRequest\x1a .indexall.v1.RemoveAliasResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/tags/aliases/{alias_id}\x12r\n" +
	"\tAddParent\x12\x1d.indexall.v1.AddParentRequest\x1a\x1e.indexall.v1.AddParentResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/tags/{child_id}/parents\x12\x84\x01\n" +
	"\fRemoveParent\x12 .indexall.v1.RemoveParentRequest\x1a!.indexall.v1.RemoveParentResponse\"/\x82\xd3\xe4\x93\x02)*'/v1/tags/{child_id}/parents/{parent_id}BFZDgithub.com/construct/indexall/internal/gen/pb/indexall/v1;indexallv1b\x06proto3"

var (
	file_indexall_v1_tag_proto_rawDescOnce sync.Once
	file_indexall_v1_tag_proto_rawDescData []byte
)

func file_indexall_v1_tag_proto_rawDescGZIP() []byte {
	file_indexall_v1_tag_proto_rawDescOnce.Do(func() {
		file_indexall_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexall_v1_tag_proto_rawDesc), len(file_indexall_v1_tag_proto_rawDesc)))
	})
	return file_indexall_v1_tag_proto_rawDescData
}

var file_indexall_v1_tag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_indexall_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_indexall_v1_tag_proto_goTypes = []any{
	(SearchTagsRequest_TagScope)(0), // 0: indexall.v1.SearchTagsRequest.TagScope
	(*Tag)(nil),                     // 1: indexall.v1.Tag
	(*CreateTagRequest)(nil),        // 2: indexall.v1.CreateTagRequest
	(*CreateTagResponse)(nil),       // 3: indexall.v1.CreateTagResponse
	(*UpdateTagRequest)(nil),        // 4: indexall.v1.UpdateTagRequest
	(*UpdateTagResponse)(nil),       // 5: indexall.v1.UpdateTagResponse
	(*DeleteTagRequest)(nil),        // 6: indexall.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil),       // 7: indexall.v1.DeleteTagResponse
	(*ListTagsRequest)(nil),         // 8: indexall.v1.ListTagsRequest
	(*ListTagsResponse)(nil),        // 9: indexall.v1.ListTagsResponse
	(*TagListItem)(nil),             // 10: indexall.v1.TagListItem
	(*TagTreeNode)(nil),             // 11: indexall.v1.TagTreeNode
	(*GetTreeRequest)(nil),          // 12: indexall.v1.GetTreeRequest
	(*GetTreeResponse)(nil),         // 13: indexall.v1.GetTreeResponse
	(*SearchTagsRequest)(nil),       // 14: indexall.v1.SearchTagsRequest
	(*SearchTagsResponse)(nil),      // 15: indexall.v1.SearchTagsResponse
	(*TagSearchResult)(nil),         // 16: indexall.v1.TagSearchResult
	(*AddAliasRequest)(nil),         // 17: indexall.v1.AddAliasRequest
	(*AddAliasResponse)(nil),        // 18: indexall.v1.AddAliasResponse
	(*RemoveAliasRequest)(nil),      // 19: indexall.v1.RemoveAliasRequest
	(*RemoveAliasResponse)(nil),     // 20: indexall.v1.RemoveAliasResponse
	(*AddParentRequest)(nil),        // 21: indexall.v1.AddParentRequest
	(*AddParentResponse)(nil),       // 22: indexall.v1.AddParentResponse
	(*RemoveParentRequest)(nil),     // 23: indexall.v1.RemoveParentRequest
	(*RemoveParentResponse)(nil),    // 24: indexall.v1.RemoveParentResponse
}
var file_indexall_v1_tag_proto_depIdxs = []int32{
	10, // 0: indexall.v1.ListTagsResponse.tags:type_name -> indexall.v1.TagListItem
	11, // 1: indexall.v1.TagTreeNode.children:type_name -> indexall.v1.TagTreeNode
	11, // 2: indexall.v1.GetTreeResponse.roots:type_name -> indexall.v1.TagTreeNode
	0,  // 3: indexall.v1.SearchTagsRequest.tag_scope:type_name -> indexall.v1.SearchTagsRequest.TagScope
	16, // 4: indexall.v1.SearchTagsResponse.results:type_name -> indexall.v1.TagSearchResult
	2,  // 5: indexall.v1.TagService.Create:input_type -> indexall.v1.CreateTagRequest
	4,  // 6: indexall.v1.TagService.Update:input_type -> indexall.v1.UpdateTagRequest
	6,  // 7: indexall.v1.TagService.Delete:input_type -> indexall.v1.DeleteTagRequest
	8,  // 8: indexall.v1.TagService.List:input_type -> indexall.v1.ListTagsRequest
	12, // 9: indexall.v1.TagService.GetTree:input_type -> indexall.v1.GetTreeRequest
	14, // 10: indexall.v1.TagService.Search:input_type -> indexall.v1.SearchTagsRequest
	17, // 11: indexall.v1.TagService.AddAlias:input_type -> indexall.v1.AddAliasRequest
	19, // 12: indexall.v1.TagService.RemoveAlias:input_type -> indexall.v1.RemoveAliasRequest
	21, // 13: indexall.v1.TagService.AddParent:input_type -> indexall.v1.AddParentRequest
	23, // 14: indexall.v1.TagService.RemoveParent:input_type -> indexall.v1.RemoveParentRequest
	3,  // 15: indexall.v1.TagService.Create:output_type -> indexall.v1.CreateTagResponse
	5,  // 16: indexall.v1.TagService.Update:output_type -> indexall.v1.UpdateTagResponse
	7,  // 17: indexall.v1.TagService.Delete:output_type -> indexall.v1.DeleteTagResponse
	9,  // 18: indexall.v1.TagService.List:output_type -> indexall.v1.ListTagsResponse
	13, // 19: indexall.v1.TagService.GetTree:output_type -> indexall.v1.GetTreeResponse
	15, // 20: indexall.v1.TagService.Search:output_type -> indexall.v1.SearchTagsResponse
	18, // 21: indexall.v1.TagService.AddAlias:output_type -> indexall.v1.AddAliasResponse
	20, // 22: indexall.v1.TagService.RemoveAlias:output_type -> indexall.v1.RemoveAliasResponse
	22, // 23: indexall.v1.TagService.AddParent:output_type -> indexall.v1.AddParentResponse
	24, // 24: indexall.v1.TagService.RemoveParent:output_type -> indexall.v1.RemoveParentResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_indexall_v1_tag_proto_init() }
func file_indexall_v1_tag_proto_init() {
	if File_indexall_v1_tag_proto != nil {
		return
	}
	file_indexall_v1_tag_proto_msgTypes[0].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[1].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[2].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[3].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[9].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[10].OneofWrappers = []any{}
	file_indexall_v1_tag_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexall_v1_tag_proto_rawDesc), len(file_indexall_v1_tag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexall_v1_tag_proto_goTypes,
		DependencyIndexes: file_indexall_v1_tag_proto_depIdxs,
		EnumInfos:         file_indexall_v1_tag_proto_enumTypes,
		MessageInfos:      file_indexall_v1_tag_proto_msgTypes,
	}.Build()
	File_indexall_v1_tag_proto = out.File
	file_indexall_v1_tag_proto_goTypes = nil
	file_indexall_v1_tag_proto_depIdxs = nil
}
