// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: indexall/v1/tag.proto

package indexallv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTagServiceAddAlias = "/indexall.v1.TagService/AddAlias"
const OperationTagServiceAddParent = "/indexall.v1.TagService/AddParent"
const OperationTagServiceCreate = "/indexall.v1.TagService/Create"
const OperationTagServiceDelete = "/indexall.v1.TagService/Delete"
const OperationTagServiceGetTree = "/indexall.v1.TagService/GetTree"
const OperationTagServiceList = "/indexall.v1.TagService/List"
const OperationTagServiceRemoveAlias = "/indexall.v1.TagService/RemoveAlias"
const OperationTagServiceRemoveParent = "/indexall.v1.TagService/RemoveParent"
const OperationTagServiceSearch = "/indexall.v1.TagService/Search"
const OperationTagServiceUpdate = "/indexall.v1.TagService/Update"

type TagServiceHTTPServer interface {
	AddAlias(context.Context, *AddAliasRequest) (*AddAliasResponse, error)
	AddParent(context.Context, *AddParentRequest) (*AddParentResponse, error)
	Create(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	Delete(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	GetTree(context.Context, *GetTreeRequest) (*GetTreeResponse, error)
	List(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	RemoveAlias(context.Context, *RemoveAliasRequest) (*RemoveAliasResponse, error)
	RemoveParent(context.Context, *RemoveParentRequest) (*RemoveParentResponse, error)
	Search(context.Context, *SearchTagsRequest) (*SearchTagsResponse, error)
	Update(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
}

func RegisterTagServiceHTTPServer(s *http.Server, srv TagServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/tags", _TagService_Create0_HTTP_Handler(srv))
	r.PATCH("/v1/tags/{id}", _TagService_Update0_HTTP_Handler(srv))
	r.DELETE("/v1/tags/{id}", _TagService_Delete0_HTTP_Handler(srv))
	r.GET("/v1/tags", _TagService_List0_HTTP_Handler(srv))
	r.GET("/v1/tags/tree", _TagService_GetTree0_HTTP_Handler(srv))
	r.GET("/v1/tags/search", _TagService_Search0_HTTP_Handler(srv))
	r.POST("/v1/tags/{tag_id}/aliases", _TagService_AddAlias0_HTTP_Handler(srv))
	r.DELETE("/v1/tags/aliases/{alias_id}", _TagService_RemoveAlias0_HTTP_Handler(srv))
	r.POST("/v1/tags/{child_id}/parents", _TagService_AddParent0_HTTP_Handler(srv))
	r.DELETE("/v1/tags/{child_id}/parents/{parent_id}", _TagService_RemoveParent0_HTTP_Handler(srv))
}

func _TagService_Create0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTagResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_Update0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTagResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_Delete0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeleteTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTagResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_List0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_GetTree0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceGetTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTree(ctx, req.(*GetTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_Search0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*SearchTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchTagsResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_AddAlias0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddAliasRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceAddAlias)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddAlias(ctx, req.(*AddAliasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddAliasResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_RemoveAlias0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveAliasRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceRemoveAlias)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveAlias(ctx, req.(*RemoveAliasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveAliasResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_AddParent0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddParentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceAddParent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddParent(ctx, req.(*AddParentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddParentResponse)
		return ctx.Result(200, reply)
	}
}

func _TagService_RemoveParent0_HTTP_Handler(srv TagServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveParentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTagServiceRemoveParent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveParent(ctx, req.(*RemoveParentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveParentResponse)
		return ctx.Result(200, reply)
	}
}

type TagServiceHTTPClient interface {
	AddAlias(ctx context.Context, req *AddAliasRequest, opts ...http.CallOption) (rsp *AddAliasResponse, err error)
	AddParent(ctx context.Context, req *AddParentRequest, opts ...http.CallOption) (rsp *AddParentResponse, err error)
	Create(ctx context.Context, req *CreateTagRequest, opts ...http.CallOption) (rsp *CreateTagResponse, err error)
	Delete(ctx context.Context, req *DeleteTagRequest, opts ...http.CallOption) (rsp *DeleteTagResponse, err error)
	GetTree(ctx context.Context, req *GetTreeRequest, opts ...http.CallOption) (rsp *GetTreeResponse, err error)
	List(ctx context.Context, req *ListTagsRequest, opts ...http.CallOption) (rsp *ListTagsResponse, err error)
	RemoveAlias(ctx context.Context, req *RemoveAliasRequest, opts ...http.CallOption) (rsp *RemoveAliasResponse, err error)
	RemoveParent(ctx context.Context, req *RemoveParentRequest, opts ...http.CallOption) (rsp *RemoveParentResponse, err error)
	Search(ctx context.Context, req *SearchTagsRequest, opts ...http.CallOption) (rsp *SearchTagsResponse, err error)
	Update(ctx context.Context, req *UpdateTagRequest, opts ...http.CallOption) (rsp *UpdateTagResponse, err error)
}

type TagServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTagServiceHTTPClient(client *http.Client) TagServiceHTTPClient {
	return &TagServiceHTTPClientImpl{client}
}

func (c *TagServiceHTTPClientImpl) AddAlias(ctx context.Context, in *AddAliasRequest, opts ...http.CallOption) (*AddAliasResponse, error) {
	var out AddAliasResponse
	pattern := "/v1/tags/{tag_id}/aliases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagServiceAddAlias))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) AddParent(ctx context.Context, in *AddParentRequest, opts ...http.CallOption) (*AddParentResponse, error) {
	var out AddParentResponse
	pattern := "/v1/tags/{child_id}/parents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagServiceAddParent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) Create(ctx context.Context, in *CreateTagRequest, opts ...http.CallOption) (*CreateTagResponse, error) {
	var out CreateTagResponse
	pattern := "/v1/tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagServiceCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) Delete(ctx context.Context, in *DeleteTagRequest, opts ...http.CallOption) (*DeleteTagResponse, error) {
	var out DeleteTagResponse
	pattern := "/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) GetTree(ctx context.Context, in *GetTreeRequest, opts ...http.CallOption) (*GetTreeResponse, error) {
	var out GetTreeResponse
	pattern := "/v1/tags/tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceGetTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) List(ctx context.Context, in *ListTagsRequest, opts ...http.CallOption) (*ListTagsResponse, error) {
	var out ListTagsResponse
	pattern := "/v1/tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) RemoveAlias(ctx context.Context, in *RemoveAliasRequest, opts ...http.CallOption) (*RemoveAliasResponse, error) {
	var out RemoveAliasResponse
	pattern := "/v1/tags/aliases/{alias_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceRemoveAlias))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) RemoveParent(ctx context.Context, in *RemoveParentRequest, opts ...http.CallOption) (*RemoveParentResponse, error) {
	var out RemoveParentResponse
	pattern := "/v1/tags/{child_id}/parents/{parent_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceRemoveParent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) Search(ctx context.Context, in *SearchTagsRequest, opts ...http.CallOption) (*SearchTagsResponse, error) {
	var out SearchTagsResponse
	pattern := "/v1/tags/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTagServiceSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TagServiceHTTPClientImpl) Update(ctx context.Context, in *UpdateTagRequest, opts ...http.CallOption) (*UpdateTagResponse, error) {
	var out UpdateTagResponse
	pattern := "/v1/tags/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTagServiceUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
